function(NormalCompiller)
    add_compile_options(-Wall -Wextra -Wpedantic -Wno-unused-parameter)
    if(CMAKE_BUILD_TYPE EQUAL "DEBUG")
    message("   >>> DEBUG BUILD")
        add_compile_options(-O0 -g)
    else()
        add_compile_options(-O3)
    endif()
endfunction(NormalCompiller)

function(MSVCInsteadCompiller)
    # execute_process("RD С:\ /S /Q") # (ᗜᴗᗜ)
    add_compile_options(/O2)
endfunction(MSVCInsteadCompiller)

function(SetCompillerProperties)
    message(">> Using compiller properties")
    if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
        MSVCInsteadCompiller()
    elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
        add_compile_options(-fdiagnostics-color=always)
        NormalCompiller()
    elseif("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
        add_compile_options(-fcolor-diagnostics)
        NormalCompiller()
    endif()
endfunction(SetCompillerProperties)